### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ThomasChr**

### CODE REVIEW

**Comment by incruder1** [comment]
u havent done anything useful.  so im not accepting it

**Comment by ThomasChr** [comment]
I fixed your typos - that's not useful?
So what...

**Comment by incruder1** [comment]
so what..
thats doesn't matter . still im not accepting.

**Comment by ThomasChr** [comment]
Glad you fixed it yourself. Good I could help.
PS: You should maybe remove the hacktoberfest topic until there is something in this repo. Apart from only one Readme sentence.

**Comment by ThomasChr** [comment]
At least now there is no typo in this one sentence. Apart from the space between secrets and the ending dot. Which is not correct. But I'm sure you will fix that too, sometime.

**Pull request closed without merging**
